services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - default

  full-stack:
    build: ./full-stack
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - default
